version: '3.7'
services:
  mssql:
    container_name: mssql2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: P@ssword!23
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
    - 1433:1433
    volumes: 
    - ./mssql-root/data:/var/opt/mssql/data
    networks:
      - keycloak-dev-network

  mssqlscripts: #Creates the Keycloak DB once
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "P@ssword!23" -Q "create database Keycloak"; do sleep 5; done'
    networks:
      - keycloak-dev-network

  kc_dev_1:
    container_name: kc_dev_1
    image: quay.io/keycloak/keycloak:11.0.0
    volumes:
      - ./keycloak-data/export/realm-export.json:/tmp/realm-export.json
      - ./keycloak-data/themes/custom:/opt/jboss/keycloak/standalone/deployments
    environment:
      DB_VENDOR: mssql
      DB_ADDR: mssql
      DB_USER: sa
      DB_PASSWORD: P@ssword!23
      DB_DATABASE: keycloak
      KEYCLOAK_FRONTEND_URL: "http://localhost:8000/auth/"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      CACHE_OWNERS_COUNT: 2
      CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS,remove_all_data_on_view_change=true"
    restart: on-failure
    depends_on:
      - mssql
    links:
      - "mailhog:smtp"
    networks:
      - keycloak-dev-network

  kc_dev_2:
    container_name: kc_dev_2
    image: quay.io/keycloak/keycloak:11.0.0
    volumes:
      - ./keycloak-data/export/realm-export.json:/tmp/realm-export.json
      - ./keycloak-data/themes/custom:/opt/jboss/keycloak/standalone/deployments
    environment:
      DB_VENDOR: mssql
      DB_ADDR: mssql
      DB_USER: sa
      DB_PASSWORD: P@ssword!23
      DB_DATABASE: keycloak
      KEYCLOAK_FRONTEND_URL: "http://localhost:8000/auth/"
      PROXY_ADDRESS_FORWARDING: "true"
      CACHE_OWNERS_COUNT: 2
      CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS,remove_all_data_on_view_change=true"
    restart: on-failure
    depends_on:
      - mssql
    links:
      - "mailhog:smtp"
    networks:
      - keycloak-dev-network

  loadbal_nginx: #Loadbalance for Keycloak Instances
    container_name: loadbal_nginx
    image: nginx:alpine
    logging:
      driver: none
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8000"
    depends_on:
      - kc_dev_1
      - kc_dev_2
    links:
      - "mailhog:smtp"
    networks:
      - keycloak-dev-network

  mailhog: #Mailserver
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - keycloak-dev-network


networks:
  keycloak-dev-network:
    driver: bridge
